# suppress inspection "UnusedProperty" for whole file
task-execution:
  # negative value is a percent of available processors (default is a half)
  # positive is literal number of threads
  # allowed values: [-100..-1] ∪ [1..Integer.MAX_VALUE]
  parallelism: -50
  await-termination-for-ms: 1
  # limits maximum statements executed by a single task
  # indirectly limits RAM and CPU usage
  # the only resource limit supported on GraalVM Community Edition
  # (and the only stable one in all editions)
  statementLimit: 1000000000000000000
springdoc:
  swagger-ui:
    displayOperationId: true
    oauth:
      realm: JsExecutor
      clientId: swagger-ui-local
      usePkceWithAuthorizationCodeGrant: true
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak:8443/realms/JsExecutor
  mvc:
    async:
      request-timeout: 3600000
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080
  ssl:
    enabled: true
    key-alias: tomcat-localhost
    key-password: password
    key-store: classpath:js-executor-key-store.p12
    key-store-password: password
    key-store-provider: SUN
    key-store-type: JKS
    # trust-store property here isn't mapped to javax.net.ssl.trustStore but is used by Spring for something else
  # so we define a custom property ourselves and use it in io.github.daniil547.js_executor_rest.SecurityConfig#configureSSL()
  javax:
    net:
      ssl:
        trust-store: classpath:truststore.jks
        trust-store-password: password
        trust-store-provider: SUN
        trust-store-type: JKS

