version: "3.9"

services:
  postgres:
    container_name: postgres
    image: "postgres:14.5"
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_DB: "kc_db"
      POSTGRES_USER: "kc_db_admin"
      POSTGRES_PASSWORD: "kc_db_admin"
    ports:
      - "5432:5432"
      #command: # debug level
      #- "-d 3"
  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:6.12"
    environment:
      PGADMIN_DEFAULT_EMAIL: abc@abc.com
      PGADMIN_DEFAULT_PASSWORD: abc
    ports:
      - "5050:80"
    networks:
      - backend
  keycloak:
    container_name: keycloak
    image: "quay.io/keycloak/keycloak:19.0.1"
    volumes:
      - ./cert:/cert/
    command:
      - "start-dev --https-key-store-file=/cert/kc-key-store.p12"
    depends_on:
      - "postgres"
    environment:
      - KC_DB=postgres
      - KC_DB_USERNAME=kc_db_admin
      - KC_DB_PASSWORD=kc_db_admin
      - KC_DB_URL=jdbc:postgresql://postgres:5432/kc_db
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_REALM_NAME=master
      - KEYCLOAK_ENABLE_TLS=true
    ports:
      - "8081:8443" # https
      - "8082:8080" # http
      - "8787:8787" # debug port
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge

